// Generated by CoffeeScript 1.9.0
(function() {
  var Vnetlabui;

  Vnetlabui = window.Vnetlabui = Ember.Application.create();

  require('scripts/controllers/*');

  require('scripts/store');

  require('scripts/models/*');

  require('scripts/routes/*');

  require('scripts/components/*');

  require('scripts/views/*');

  require('scripts/router');

}).call(this);
